### ISSUE TITLE
连接standalone模式启动的nacos时候，serverlist报404

### ISSUE THREAD

**Issue by jiangzhuo** [nacos-group/nacos-sdk-nodejs#10]
standalone模式启动的，应该没有serverlist的接口。
log如下

  cluster-client [ClusterClient:DiamondClient@127.0.0.1:8848] init cluster client, try to seize the leader on port:7777 +0ms
  cluster-client:server listen 7777 success +0ms
  diamond-client:snapshot 0.7743671956236662 +0ms
  cluster-client [ClusterClient:DiamondClient@127.0.0.1:8848] has seized port 7777, and serves as leader client. +8ms
  nacos:9342:ins-496:client_worker client worker start +0ms
  nacos:9342:ins-496:client_worker calling getConfig, dataId: test, group: DEFAULT_GROUP +1ms
  urllib Request#1 GET http://127.0.0.1:8848/nacos/serverlist with headers {"User-Agent":"node-urllib/2.31.3 Node.js/10.13.0 (Linux 4.19; x64)"}, options.path: /nacos/serverlist +0ms
  urllib ConnectTimeout: 6000, ResponseTimeout: 6000 +1ms
  urllib Connect timer ticking, timeout: 6000 +2ms
  urllib Response timer ticking, timeout: 6000 +3ms
  urllib Request#1 http://127.0.0.1:8848/nacos/serverlist new socket connected +0ms
  urllib Request#1 http://127.0.0.1:8848/nacos/serverlist `req response` event emit: status 404, headers: {"content-type":"application/json;charset=UTF-8","transfer-encoding":"chunked","date":"Tue, 11 Dec 2018 20:54:41 GMT"} +109ms
  urllib Request#1 http://127.0.0.1:8848/nacos/serverlist: `res data` event emit, size 137 +1ms
  urllib Request#1 http://127.0.0.1:8848/nacos/serverlist: `res end` event emit, total size 137, _dumped: false +0ms
  urllib [118ms] done, 137 bytes HTTP 404 GET 127.0.0.1 /nacos/serverlist, keepAliveSocket: false, timing: null, socketHandledRequests: 1, socketHandledResponses: 1 +1ms

[Wed Dec 12 2018 04:54:41 GMT+0800 (China Standard Time)][pid: 9342][NacosConfigClient] NacosServerResponseError: [Nacos#ServerListManager] request url: http://127.0.0.1:8848/nacos/serverlist failed with statusCode: 404 
Error Stack:
  NacosServerResponseError: [Nacos#ServerListManager] request url: http://127.0.0.1:8848/nacos/serverlist failed with statusCode: 404
    at ServerListManager.request (/home/jiangzhuo/Desktop/test-client/node_modules/nacos-config/src/server_list_mgr.ts:126:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error Additions:
  url: "http://127.0.0.1:8848/nacos/serverlist"
  params: {"timeout":6000,"dataType":"text","requestUrls":["http://127.0.0.1:8848/nacos/serverlist"],"maxRedirects":10}
  body: "{\"timestamp\":\"2018-12-11T20:54:41.199+0000\",\"status\":404,\"error\":\"Not Found\",\"message\":\"No message available\",\"path\":\"/nacos/serverlist\"}"

**Comment by czy88840616** [comment]
恩，默认是寻址，如果不希望寻址，只是一个单服务器的话，配置 serverAddr 属性。

```
const configClient = new NacosConfigClient({
  serverAddr: '127.0.0.1:8080',
});
```

**Comment by jiangzhuo** [comment]
谢谢
