### ISSUE TITLE
[优化] subscribe config listener 触发逻辑

### ISSUE THREAD

**Issue by SaltFish001** [nacos-group/nacos-sdk-nodejs#103]
listener应该在订阅的config变化时才触发，不应该在订阅后立即触发一次。
我看了逻辑， 你们会在订阅后获取一次数据并保存。并立即触发一次listener，这不符合直觉。如果没注意会导致无限触发

**Comment by xhavit** [comment]
这个现在解决了吗？2.2.1就有这个问题

**Comment by SaltFish001** [comment]
> 

放弃了，转投Consul了，然后发现Consul的SDK也是这样设计的。可能理解不一致把

**Comment by xhavit** [comment]
是不是为了方便订阅实现的方便，调用subscribe就不用再调用getConfig了？这样想似乎有点道理
