### ISSUE TITLE
使用 endpoint 方式获取 NameProxy 服务信息，获取失败时的优化问题

### ISSUE THREAD

**Issue by KenyeeC** [nacos-group/nacos-sdk-nodejs#121]
### 问题
目前使用 endpoint 方式获取 NameProxy 服务信息，如果获取失败，会等待 30 秒，然后重新获取。但是对于使用方的应用服务来说，在获取服务信息失败后，应用服务依然启动起来了，这个时候如果使用到相关的 NameProxy 的服务的时候，就必然会失败，必须等待 30 秒后才能重试从而恢复正常的服务

### 建议
思路一：在 [serversFromEndpoint](https://github.com/nacos-group/nacos-sdk-nodejs/blob/master/packages/nacos-naming/lib/naming/proxy.js#L105) 为空的情况下，允许通过另外的配置调整重试时长，待有值后再使用回原来的轮训时间

思路二：在 [_init](https://github.com/nacos-group/nacos-sdk-nodejs/blob/master/packages/nacos-naming/lib/naming/proxy.js#L112) 函数中阻塞启动，直到  [serversFromEndpoint](https://github.com/nacos-group/nacos-sdk-nodejs/blob/master/packages/nacos-naming/lib/naming/proxy.js#L105) 有值

**Comment by czy88840616** [comment]
这个 30s 好像是固定的限制，属于对服务端的保护，如果少于 30s 可能会导致服务端压力过大了。

**Comment by KenyeeC** [comment]
这个保护的机制没有问题，但是我感觉可以更灵活一些，在没有获取到实际的配置之前，这个轮询可以短一点，比如十秒，等拿到配置后，后面的轮询都在30秒都没关系了

我们的场景是，有一个应用部署到很多个容器，然后偶尔会有一个容器因为网络问题没有拿到相关配置，但是需要等待30秒才能恢复，这个时间段服务还是能正常起起来，但是如果有流量打进来的话，就会响应失败。所以我们希望这个恢复能快一点

**Comment by czy88840616** [comment]
我记得服务端有30s 的限制，要找人确认下

**Comment by KenyeeC** [comment]
> 我记得服务端有30s 的限制，要找人确认下

早上好，请问下这个服务端限制是否确认到了？

**Comment by czy88840616** [comment]
问了一下，目前这个机制服务端本身没有限制，但是由于和 java 版本保持一致，所以服务端同学不建议动这个参数。如果初始化有错误，就不建议继续启动了。
