### ISSUE TITLE
支持namespace的方式

### ISSUE THREAD

**Issue by bing086** [nacos-group/nacos-sdk-nodejs#17]
无法支持namespace，namespaceId为实际注册导致无法。尝试修改注册也无效。

  async registerService(serviceName, instance) {
    this.logger.info('[NameProxy][REGISTER-SERVICE] registering service: %s with instance:%j', serviceName, instance);

    const params = {
      namespaceId: '3c239366-d993-489a-afbe-89e53160117f', //自定义命名空间
      ip: instance.ip,
      port: instance.port + '',
      weight: instance.weight + '',
      enable: instance.enabled ? 'true' : 'false',
      healthy: instance.healthy ? 'true' : 'false',
      metadata: JSON.stringify(instance.metadata),
      clusterName: instance.clusterName,
      serviceName,
    };
    console.log('registerService:',params);
    return await this.reqAPI(Constants.NACOS_URL_INSTANCE, params, 'PUT');
  }

**Comment by bing086** [comment]
![image](https://user-images.githubusercontent.com/700861/55939173-b045cb00-5c6f-11e9-8121-574232b69277.png)
![image](https://user-images.githubusercontent.com/700861/55939205-c2c00480-5c6f-11e9-9540-18a0ae94c4d6.png)
![image](https://user-images.githubusercontent.com/700861/55939213-cb183f80-5c6f-11e9-8a90-c19bab209311.png)


尝试修改。测试成功

**Comment by czy88840616** [comment]
给我们提个 pr？🌹

**Comment by gxcsoccer** [comment]
已经支持
