### ISSUE TITLE
注册成功了，但是nacos前端界面没显示

### ISSUE THREAD

**Issue by badounan** [nacos-group/nacos-sdk-nodejs#23]
注册成功了，但是nacos前端界面没显示
![image](https://user-images.githubusercontent.com/16603013/57367941-94750c80-71bc-11e9-98a5-8d8e3bc63367.png)

**Comment by gxcsoccer** [comment]
nacos 什么版本？ 你用的 sdk 什么版本？

**Comment by gxcsoccer** [comment]
![image](https://user-images.githubusercontent.com/1207064/57370269-511d9c80-71c2-11e9-8551-8280ea79cf4d.png)

console 默认的命名空间是 `public`，而 sdk 默认的是 `default`

**Comment by gxcsoccer** [comment]
在初始化时需要传入 namespace

```js
  const client = new NacosNamingClient({
    logger,
    serverList: '127.0.0.1:8848',
    namespace: 'public',
  });
```

**Comment by badounan** [comment]
增加namespace: 'public'可以了，谢谢！
