### ISSUE TITLE
Initialization of NacosNamingClient, injection instance is problematic

### ISSUE THREAD

**Issue by huangqinghe** [nacos-group/nacos-sdk-nodejs#25]
I created a NamingService class in midway and initialized NacosNamingClient. Then when I injected this NamingService class into other classes, I threw an exception when accessing the request. I suspected initially that it was `await this. nacosClient. ready () ` code problem. Please check it.
![image](https://user-images.githubusercontent.com/8857314/57420579-bf9e4100-723a-11e9-8ee8-c70d8bcb281a.png)
![image](https://user-images.githubusercontent.com/8857314/57420593-d17fe400-723a-11e9-82c7-d1b1be7f005d.png)
异常信息：
![image](https://user-images.githubusercontent.com/8857314/57420624-e8263b00-723a-11e9-9f2b-250af956ad77.png)

**Comment by gxcsoccer** [comment]
@huangqinghe you should create an issue in MidwayJS group.

**Comment by huangqinghe** [comment]
> @huangqinghe you should create an issue in [MidwayJS group](https://github.com/midwayjs/midway/issues).

This is not a midway problem. It is suspected that the nacos-sdk-node JS client is compatible with windows.

![image](https://user-images.githubusercontent.com/8857314/57441295-34459f80-727c-11e9-9fdc-03d2e795300c.png)
![image](https://user-images.githubusercontent.com/8857314/57441319-432c5200-727c-11e9-932c-d726c0504392.png)

**Comment by gxcsoccer** [comment]
@huangqinghe Please provide reproduce code and more detail error stack.

**Comment by huangqinghe** [comment]
> @huangqinghe Please provide reproduce code and more detail error stack.

reproduce code：
[midway-demo.zip](https://github.com/nacos-group/nacos-sdk-nodejs/files/3164755/midway-demo.zip)
This code runs on Windows and has the following exceptions，more detail error stack：
![image](https://user-images.githubusercontent.com/8857314/57500179-02344c00-7315-11e9-9be8-357e8398dacf.png)
