### ISSUE TITLE
How to create NacosConfigClient with username and password?

### ISSUE THREAD

**Issue by Vwings** [nacos-group/nacos-sdk-nodejs#40]
My nacos server has username and password, but I can't find the `username` and `password` fields in the `ClientOptions` interface.

```js
const configClient = new NacosConfigClient({
    serverAddr: 'ip',
    namespace: 'namesapce',
    username: 'username',
    password: 'password'
});
```
Nacos nodejs sdk version: `2.0.0`.

**Comment by inetufo** [comment]
Here is the pull request https://github.com/nacos-group/nacos-sdk-nodejs/pull/39.
Hope to merge into master @czy88840616

**Comment by Vwings** [comment]
Typescript declaration file is not updated in `2.1.0`,  I used `// @ts-ignore` to fix this.
```ts
const configClient = new NacosConfigClient({
  serverAddr: 'xxx',
  namespace: 'xxx',
  // @ts-ignore
  username: 'xxx',
  password: 'xxx',
});
```
