### ISSUE TITLE
Error: Cannot create a string longer than 0x3fffffe7 characters (address: 127.0.0.1:7777)

### ISSUE THREAD

**Issue by brucewar** [nacos-group/nacos-sdk-nodejs#59]
Node.js: 10.0.0
nacos-sdk-nodejs: 2.1.1
系统：CentOS7

egg.js连接nacos报错如下：
![image](https://user-images.githubusercontent.com/4013475/127252487-167b9da5-246b-4ced-a1be-902c373644ae.png)

**Comment by nsuedu** [comment]
same problem

```
const NacosConfigClient = require('nacos').NacosConfigClient; // js

async function test() {
  const configClient = new NacosConfigClient({
    serverAddr: `${NACOS_SERVER_HOST}:${NACOS_SERVER_PORT}`,
    namespace: NACOS_NAMESPACE,
  });

  console.log('getConfig11 = ', configClient);


}

test();

```


case :

[NacosConfigClient] Error: Cannot create a string longer than 0x1fffffe8 characters (address: 127.0.0.1:7777) 
Error Stack:
  Error: Cannot create a string longer than 0x1fffffe8 characters

**Comment by wangliqiang1026** [comment]
请问最后解决了吗？遇到了相同的问题

**Comment by brucewar** [comment]
> 请问最后解决了吗？遇到了相同的问题

解决了，端口占用问题

**Comment by wangliqiang1026** [comment]
> > 请问最后解决了吗？遇到了相同的问题
> 
> 解决了，端口占用问题

感谢，难怪我的突然又正常了
